package model

import "time"

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Account struct {
	SecuritiesAccount MarginAccount     `json:"securitiesAccount,omitempty"`
	AggregatedBalance AggregatedBalance `json:"aggregatedBalance,omitempty"`
}

type AggregatedBalance struct {
	CurrentLiquidationValue float64
	LiquidationValue        float64
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountApiOptionDeliverable struct {
	Symbol           string     `json:"symbol,omitempty"`
	DeliverableUnits float64    `json:"deliverableUnits,omitempty"`
	ApiCurrencyType  string     `json:"apiCurrencyType,omitempty"`
	AssetType        *AssetType `json:"assetType,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountCashEquivalent struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
	Type_        string  `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountEquity struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountFixedIncome struct {
	AssetType    string    `json:"assetType"`
	Cusip        string    `json:"cusip,omitempty"`
	Symbol       string    `json:"symbol,omitempty"`
	Description  string    `json:"description,omitempty"`
	InstrumentId int64     `json:"instrumentId,omitempty"`
	NetChange    float64   `json:"netChange,omitempty"`
	MaturityDate time.Time `json:"maturityDate,omitempty"`
	Factor       float64   `json:"factor,omitempty"`
	VariableRate float64   `json:"variableRate,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountMutualFund struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountNumberHash struct {
	AccountNumber string `json:"accountNumber,omitempty"`
	HashValue     string `json:"hashValue,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountOption struct {
	AssetType          string                        `json:"assetType"`
	Cusip              string                        `json:"cusip,omitempty"`
	Symbol             string                        `json:"symbol,omitempty"`
	Description        string                        `json:"description,omitempty"`
	InstrumentId       int64                         `json:"instrumentId,omitempty"`
	NetChange          float64                       `json:"netChange,omitempty"`
	OptionDeliverables []AccountApiOptionDeliverable `json:"optionDeliverables,omitempty"`
	PutCall            string                        `json:"putCall,omitempty"`
	OptionMultiplier   int32                         `json:"optionMultiplier,omitempty"`
	Type_              string                        `json:"type,omitempty"`
	UnderlyingSymbol   string                        `json:"underlyingSymbol,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountsBaseInstrument struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AccountsInstrument struct {
	AccountCashEquivalent
	AccountEquity
	AccountFixedIncome
	AccountMutualFund
	AccountOption
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AmountIndicator string

// List of amountIndicator
const (
	DOLLARS_AmountIndicator    AmountIndicator = "DOLLARS"
	SHARES_AmountIndicator     AmountIndicator = "SHARES"
	ALL_SHARES_AmountIndicator AmountIndicator = "ALL_SHARES"
	PERCENTAGE_AmountIndicator AmountIndicator = "PERCENTAGE"
	UNKNOWN_AmountIndicator    AmountIndicator = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ApiOrderStatus string

// List of apiOrderStatus
const (
	AWAITING_PARENT_ORDER_ApiOrderStatus   ApiOrderStatus = "AWAITING_PARENT_ORDER"
	AWAITING_CONDITION_ApiOrderStatus      ApiOrderStatus = "AWAITING_CONDITION"
	AWAITING_STOP_CONDITION_ApiOrderStatus ApiOrderStatus = "AWAITING_STOP_CONDITION"
	AWAITING_MANUAL_REVIEW_ApiOrderStatus  ApiOrderStatus = "AWAITING_MANUAL_REVIEW"
	ACCEPTED_ApiOrderStatus                ApiOrderStatus = "ACCEPTED"
	AWAITING_UR_OUT_ApiOrderStatus         ApiOrderStatus = "AWAITING_UR_OUT"
	PENDING_ACTIVATION_ApiOrderStatus      ApiOrderStatus = "PENDING_ACTIVATION"
	QUEUED_ApiOrderStatus                  ApiOrderStatus = "QUEUED"
	WORKING_ApiOrderStatus                 ApiOrderStatus = "WORKING"
	REJECTED_ApiOrderStatus                ApiOrderStatus = "REJECTED"
	PENDING_CANCEL_ApiOrderStatus          ApiOrderStatus = "PENDING_CANCEL"
	CANCELED_ApiOrderStatus                ApiOrderStatus = "CANCELED"
	PENDING_REPLACE_ApiOrderStatus         ApiOrderStatus = "PENDING_REPLACE"
	REPLACED_ApiOrderStatus                ApiOrderStatus = "REPLACED"
	FILLED_ApiOrderStatus                  ApiOrderStatus = "FILLED"
	EXPIRED_ApiOrderStatus                 ApiOrderStatus = "EXPIRED"
	NEW_ApiOrderStatus                     ApiOrderStatus = "NEW"
	AWAITING_RELEASE_TIME_ApiOrderStatus   ApiOrderStatus = "AWAITING_RELEASE_TIME"
	PENDING_ACKNOWLEDGEMENT_ApiOrderStatus ApiOrderStatus = "PENDING_ACKNOWLEDGEMENT"
	PENDING_RECALL_ApiOrderStatus          ApiOrderStatus = "PENDING_RECALL"
	UNKNOWN_ApiOrderStatus                 ApiOrderStatus = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ApiRuleAction string

// List of APIRuleAction
const (
	ACCEPT_ApiRuleAction  ApiRuleAction = "ACCEPT"
	ALERT_ApiRuleAction   ApiRuleAction = "ALERT"
	REJECT_ApiRuleAction  ApiRuleAction = "REJECT"
	REVIEW_ApiRuleAction  ApiRuleAction = "REVIEW"
	UNKNOWN_ApiRuleAction ApiRuleAction = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type AssetType string

// List of assetType
const (
	EQUITY_AssetType                AssetType = "EQUITY"
	MUTUAL_FUND_AssetType           AssetType = "MUTUAL_FUND"
	OPTION_AssetType                AssetType = "OPTION"
	FUTURE_AssetType                AssetType = "FUTURE"
	FOREX_AssetType                 AssetType = "FOREX"
	INDEX_AssetType                 AssetType = "INDEX"
	CASH_EQUIVALENT_AssetType       AssetType = "CASH_EQUIVALENT"
	FIXED_INCOME_AssetType          AssetType = "FIXED_INCOME"
	PRODUCT_AssetType               AssetType = "PRODUCT"
	CURRENCY_AssetType              AssetType = "CURRENCY"
	COLLECTIVE_INVESTMENT_AssetType AssetType = "COLLECTIVE_INVESTMENT"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CashAccount struct {
	Type_                   string              `json:"type,omitempty"`
	AccountNumber           string              `json:"accountNumber,omitempty"`
	RoundTrips              int32               `json:"roundTrips,omitempty"`
	IsDayTrader             bool                `json:"isDayTrader,omitempty"`
	IsClosingOnlyRestricted bool                `json:"isClosingOnlyRestricted,omitempty"`
	PfcbFlag                bool                `json:"pfcbFlag,omitempty"`
	Positions               []Position          `json:"positions,omitempty"`
	InitialBalances         *CashInitialBalance `json:"initialBalances,omitempty"`
	CurrentBalances         *CashBalance        `json:"currentBalances,omitempty"`
	ProjectedBalances       *CashBalance        `json:"projectedBalances,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CashBalance struct {
	CashAvailableForTrading      float64 `json:"cashAvailableForTrading,omitempty"`
	CashAvailableForWithdrawal   float64 `json:"cashAvailableForWithdrawal,omitempty"`
	CashCall                     float64 `json:"cashCall,omitempty"`
	LongNonMarginableMarketValue float64 `json:"longNonMarginableMarketValue,omitempty"`
	TotalCash                    float64 `json:"totalCash,omitempty"`
	CashDebitCallValue           float64 `json:"cashDebitCallValue,omitempty"`
	UnsettledCash                float64 `json:"unsettledCash,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CashInitialBalance struct {
	AccruedInterest            float64 `json:"accruedInterest,omitempty"`
	CashAvailableForTrading    float64 `json:"cashAvailableForTrading,omitempty"`
	CashAvailableForWithdrawal float64 `json:"cashAvailableForWithdrawal,omitempty"`
	CashBalance                float64 `json:"cashBalance,omitempty"`
	BondValue                  float64 `json:"bondValue,omitempty"`
	CashReceipts               float64 `json:"cashReceipts,omitempty"`
	LiquidationValue           float64 `json:"liquidationValue,omitempty"`
	LongOptionMarketValue      float64 `json:"longOptionMarketValue,omitempty"`
	LongStockValue             float64 `json:"longStockValue,omitempty"`
	MoneyMarketFund            float64 `json:"moneyMarketFund,omitempty"`
	MutualFundValue            float64 `json:"mutualFundValue,omitempty"`
	ShortOptionMarketValue     float64 `json:"shortOptionMarketValue,omitempty"`
	ShortStockValue            float64 `json:"shortStockValue,omitempty"`
	IsInCall                   bool    `json:"isInCall,omitempty"`
	UnsettledCash              float64 `json:"unsettledCash,omitempty"`
	CashDebitCallValue         float64 `json:"cashDebitCallValue,omitempty"`
	PendingDeposits            float64 `json:"pendingDeposits,omitempty"`
	AccountValue               float64 `json:"accountValue,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CollectiveInvestment struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
	Type_        string  `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Commission struct {
	CommissionLegs []CommissionLeg `json:"commissionLegs,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CommissionAndFee struct {
	Commission     *Commission `json:"commission,omitempty"`
	Fee            *Fees       `json:"fee,omitempty"`
	TrueCommission *Commission `json:"trueCommission,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CommissionLeg struct {
	CommissionValues []CommissionValue `json:"commissionValues,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CommissionValue struct {
	Value float64  `json:"value,omitempty"`
	Type_ *FeeType `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ComplexOrderStrategyType string

// List of complexOrderStrategyType
const (
	NONE_ComplexOrderStrategyType                     ComplexOrderStrategyType = "NONE"
	COVERED_ComplexOrderStrategyType                  ComplexOrderStrategyType = "COVERED"
	VERTICAL_ComplexOrderStrategyType                 ComplexOrderStrategyType = "VERTICAL"
	BACK_RATIO_ComplexOrderStrategyType               ComplexOrderStrategyType = "BACK_RATIO"
	CALENDAR_ComplexOrderStrategyType                 ComplexOrderStrategyType = "CALENDAR"
	DIAGONAL_ComplexOrderStrategyType                 ComplexOrderStrategyType = "DIAGONAL"
	STRADDLE_ComplexOrderStrategyType                 ComplexOrderStrategyType = "STRADDLE"
	STRANGLE_ComplexOrderStrategyType                 ComplexOrderStrategyType = "STRANGLE"
	COLLAR_SYNTHETIC_ComplexOrderStrategyType         ComplexOrderStrategyType = "COLLAR_SYNTHETIC"
	BUTTERFLY_ComplexOrderStrategyType                ComplexOrderStrategyType = "BUTTERFLY"
	CONDOR_ComplexOrderStrategyType                   ComplexOrderStrategyType = "CONDOR"
	IRON_CONDOR_ComplexOrderStrategyType              ComplexOrderStrategyType = "IRON_CONDOR"
	VERTICAL_ROLL_ComplexOrderStrategyType            ComplexOrderStrategyType = "VERTICAL_ROLL"
	COLLAR_WITH_STOCK_ComplexOrderStrategyType        ComplexOrderStrategyType = "COLLAR_WITH_STOCK"
	DOUBLE_DIAGONAL_ComplexOrderStrategyType          ComplexOrderStrategyType = "DOUBLE_DIAGONAL"
	UNBALANCED_BUTTERFLY_ComplexOrderStrategyType     ComplexOrderStrategyType = "UNBALANCED_BUTTERFLY"
	UNBALANCED_CONDOR_ComplexOrderStrategyType        ComplexOrderStrategyType = "UNBALANCED_CONDOR"
	UNBALANCED_IRON_CONDOR_ComplexOrderStrategyType   ComplexOrderStrategyType = "UNBALANCED_IRON_CONDOR"
	UNBALANCED_VERTICAL_ROLL_ComplexOrderStrategyType ComplexOrderStrategyType = "UNBALANCED_VERTICAL_ROLL"
	MUTUAL_FUND_SWAP_ComplexOrderStrategyType         ComplexOrderStrategyType = "MUTUAL_FUND_SWAP"
	CUSTOM_ComplexOrderStrategyType                   ComplexOrderStrategyType = "CUSTOM"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Currency struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type DateParam struct {
	// Valid ISO-8601 format is :<br> <code>yyyy-MM-dd'T'HH:mm:ss.SSSZ</code>
	Date string `json:"date,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Duration string

// List of duration
const (
	DAY_Duration                 Duration = "DAY"
	GOOD_TILL_CANCEL_Duration    Duration = "GOOD_TILL_CANCEL"
	FILL_OR_KILL_Duration        Duration = "FILL_OR_KILL"
	IMMEDIATE_OR_CANCEL_Duration Duration = "IMMEDIATE_OR_CANCEL"
	END_OF_WEEK_Duration         Duration = "END_OF_WEEK"
	END_OF_MONTH_Duration        Duration = "END_OF_MONTH"
	NEXT_END_OF_MONTH_Duration   Duration = "NEXT_END_OF_MONTH"
	UNKNOWN_Duration             Duration = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ExecutionLeg struct {
	LegId             int64     `json:"legId,omitempty"`
	Price             float64   `json:"price,omitempty"`
	Quantity          float64   `json:"quantity,omitempty"`
	MismarkedQuantity float64   `json:"mismarkedQuantity,omitempty"`
	InstrumentId      int64     `json:"instrumentId,omitempty"`
	Time              time.Time `json:"time,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type FeeLeg struct {
	FeeValues []FeeValue `json:"feeValues,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type FeeType string

// List of FeeType
const (
	COMMISSION_FeeType                FeeType = "COMMISSION"
	SEC_FEE_FeeType                   FeeType = "SEC_FEE"
	STR_FEE_FeeType                   FeeType = "STR_FEE"
	R_FEE_FeeType                     FeeType = "R_FEE"
	CDSC_FEE_FeeType                  FeeType = "CDSC_FEE"
	OPT_REG_FEE_FeeType               FeeType = "OPT_REG_FEE"
	ADDITIONAL_FEE_FeeType            FeeType = "ADDITIONAL_FEE"
	MISCELLANEOUS_FEE_FeeType         FeeType = "MISCELLANEOUS_FEE"
	FTT_FeeType                       FeeType = "FTT"
	FUTURES_CLEARING_FEE_FeeType      FeeType = "FUTURES_CLEARING_FEE"
	FUTURES_DESK_OFFICE_FEE_FeeType   FeeType = "FUTURES_DESK_OFFICE_FEE"
	FUTURES_EXCHANGE_FEE_FeeType      FeeType = "FUTURES_EXCHANGE_FEE"
	FUTURES_GLOBEX_FEE_FeeType        FeeType = "FUTURES_GLOBEX_FEE"
	FUTURES_NFA_FEE_FeeType           FeeType = "FUTURES_NFA_FEE"
	FUTURES_PIT_BROKERAGE_FEE_FeeType FeeType = "FUTURES_PIT_BROKERAGE_FEE"
	FUTURES_TRANSACTION_FEE_FeeType   FeeType = "FUTURES_TRANSACTION_FEE"
	LOW_PROCEEDS_COMMISSION_FeeType   FeeType = "LOW_PROCEEDS_COMMISSION"
	BASE_CHARGE_FeeType               FeeType = "BASE_CHARGE"
	GENERAL_CHARGE_FeeType            FeeType = "GENERAL_CHARGE"
	GST_FEE_FeeType                   FeeType = "GST_FEE"
	TAF_FEE_FeeType                   FeeType = "TAF_FEE"
	INDEX_OPTION_FEE_FeeType          FeeType = "INDEX_OPTION_FEE"
	TEFRA_TAX_FeeType                 FeeType = "TEFRA_TAX"
	STATE_TAX_FeeType                 FeeType = "STATE_TAX"
	UNKNOWN_FeeType                   FeeType = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type FeeValue struct {
	Value float64  `json:"value,omitempty"`
	Type_ *FeeType `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Fees struct {
	FeeLegs []FeeLeg `json:"feeLegs,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Forex struct {
	AssetType       string    `json:"assetType"`
	Cusip           string    `json:"cusip,omitempty"`
	Symbol          string    `json:"symbol,omitempty"`
	Description     string    `json:"description,omitempty"`
	InstrumentId    int64     `json:"instrumentId,omitempty"`
	NetChange       float64   `json:"netChange,omitempty"`
	Type_           string    `json:"type,omitempty"`
	BaseCurrency    *Currency `json:"baseCurrency,omitempty"`
	CounterCurrency *Currency `json:"counterCurrency,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Future struct {
	ActiveContract  bool      `json:"activeContract,omitempty"`
	Type_           string    `json:"type,omitempty"`
	ExpirationDate  time.Time `json:"expirationDate,omitempty"`
	LastTradingDate time.Time `json:"lastTradingDate,omitempty"`
	FirstNoticeDate time.Time `json:"firstNoticeDate,omitempty"`
	Multiplier      float64   `json:"multiplier,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Index struct {
	ActiveContract bool   `json:"activeContract,omitempty"`
	Type_          string `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Instruction string

// List of instruction
const (
	BUY_Instruction               Instruction = "BUY"
	SELL_Instruction              Instruction = "SELL"
	BUY_TO_COVER_Instruction      Instruction = "BUY_TO_COVER"
	SELL_SHORT_Instruction        Instruction = "SELL_SHORT"
	BUY_TO_OPEN_Instruction       Instruction = "BUY_TO_OPEN"
	BUY_TO_CLOSE_Instruction      Instruction = "BUY_TO_CLOSE"
	SELL_TO_OPEN_Instruction      Instruction = "SELL_TO_OPEN"
	SELL_TO_CLOSE_Instruction     Instruction = "SELL_TO_CLOSE"
	EXCHANGE_Instruction          Instruction = "EXCHANGE"
	SELL_SHORT_EXEMPT_Instruction Instruction = "SELL_SHORT_EXEMPT"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type MarginAccount struct {
	Type_                   string                `json:"type,omitempty"`
	AccountNumber           string                `json:"accountNumber,omitempty"`
	RoundTrips              int32                 `json:"roundTrips,omitempty"`
	IsDayTrader             bool                  `json:"isDayTrader,omitempty"`
	IsClosingOnlyRestricted bool                  `json:"isClosingOnlyRestricted,omitempty"`
	PfcbFlag                bool                  `json:"pfcbFlag,omitempty"`
	Positions               []Position            `json:"positions,omitempty"`
	InitialBalances         *MarginInitialBalance `json:"initialBalances,omitempty"`
	CurrentBalances         *MarginBalance        `json:"currentBalances,omitempty"`
	ProjectedBalances       *MarginBalance        `json:"projectedBalances,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type MarginBalance struct {
	AvailableFunds                   float64 `json:"availableFunds,omitempty"`
	AvailableFundsNonMarginableTrade float64 `json:"availableFundsNonMarginableTrade,omitempty"`
	BuyingPower                      float64 `json:"buyingPower,omitempty"`
	BuyingPowerNonMarginableTrade    float64 `json:"buyingPowerNonMarginableTrade,omitempty"`
	DayTradingBuyingPower            float64 `json:"dayTradingBuyingPower,omitempty"`
	DayTradingBuyingPowerCall        float64 `json:"dayTradingBuyingPowerCall,omitempty"`
	Equity                           float64 `json:"equity,omitempty"`
	EquityPercentage                 float64 `json:"equityPercentage,omitempty"`
	LongMarginValue                  float64 `json:"longMarginValue,omitempty"`
	MaintenanceCall                  float64 `json:"maintenanceCall,omitempty"`
	MaintenanceRequirement           float64 `json:"maintenanceRequirement,omitempty"`
	MarginBalance                    float64 `json:"marginBalance,omitempty"`
	RegTCall                         float64 `json:"regTCall,omitempty"`
	ShortBalance                     float64 `json:"shortBalance,omitempty"`
	ShortMarginValue                 float64 `json:"shortMarginValue,omitempty"`
	Sma                              float64 `json:"sma,omitempty"`
	IsInCall                         bool    `json:"isInCall,omitempty"`
	StockBuyingPower                 float64 `json:"stockBuyingPower,omitempty"`
	OptionBuyingPower                float64 `json:"optionBuyingPower,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type MarginInitialBalance struct {
	AccruedInterest                  float64 `json:"accruedInterest,omitempty"`
	AvailableFundsNonMarginableTrade float64 `json:"availableFundsNonMarginableTrade,omitempty"`
	BondValue                        float64 `json:"bondValue,omitempty"`
	BuyingPower                      float64 `json:"buyingPower,omitempty"`
	CashBalance                      float64 `json:"cashBalance,omitempty"`
	CashAvailableForTrading          float64 `json:"cashAvailableForTrading,omitempty"`
	CashReceipts                     float64 `json:"cashReceipts,omitempty"`
	DayTradingBuyingPower            float64 `json:"dayTradingBuyingPower,omitempty"`
	DayTradingBuyingPowerCall        float64 `json:"dayTradingBuyingPowerCall,omitempty"`
	DayTradingEquityCall             float64 `json:"dayTradingEquityCall,omitempty"`
	Equity                           float64 `json:"equity,omitempty"`
	EquityPercentage                 float64 `json:"equityPercentage,omitempty"`
	LiquidationValue                 float64 `json:"liquidationValue,omitempty"`
	LongMarginValue                  float64 `json:"longMarginValue,omitempty"`
	LongOptionMarketValue            float64 `json:"longOptionMarketValue,omitempty"`
	LongStockValue                   float64 `json:"longStockValue,omitempty"`
	MaintenanceCall                  float64 `json:"maintenanceCall,omitempty"`
	MaintenanceRequirement           float64 `json:"maintenanceRequirement,omitempty"`
	Margin                           float64 `json:"margin,omitempty"`
	MarginEquity                     float64 `json:"marginEquity,omitempty"`
	MoneyMarketFund                  float64 `json:"moneyMarketFund,omitempty"`
	MutualFundValue                  float64 `json:"mutualFundValue,omitempty"`
	RegTCall                         float64 `json:"regTCall,omitempty"`
	ShortMarginValue                 float64 `json:"shortMarginValue,omitempty"`
	ShortOptionMarketValue           float64 `json:"shortOptionMarketValue,omitempty"`
	ShortStockValue                  float64 `json:"shortStockValue,omitempty"`
	TotalCash                        float64 `json:"totalCash,omitempty"`
	IsInCall                         bool    `json:"isInCall,omitempty"`
	UnsettledCash                    float64 `json:"unsettledCash,omitempty"`
	PendingDeposits                  float64 `json:"pendingDeposits,omitempty"`
	MarginBalance                    float64 `json:"marginBalance,omitempty"`
	ShortBalance                     float64 `json:"shortBalance,omitempty"`
	AccountValue                     float64 `json:"accountValue,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Offer struct {
	Level2Permissions bool   `json:"level2Permissions,omitempty"`
	MktDataPermission string `json:"mktDataPermission,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Order struct {
	Session                  *Session                  `json:"session,omitempty"`
	Duration                 *Duration                 `json:"duration,omitempty"`
	OrderType                *OrderType                `json:"orderType,omitempty"`
	CancelTime               time.Time                 `json:"cancelTime,omitempty"`
	ComplexOrderStrategyType *ComplexOrderStrategyType `json:"complexOrderStrategyType,omitempty"`
	Quantity                 float64                   `json:"quantity,omitempty"`
	FilledQuantity           float64                   `json:"filledQuantity,omitempty"`
	RemainingQuantity        float64                   `json:"remainingQuantity,omitempty"`
	RequestedDestination     *RequestedDestination     `json:"requestedDestination,omitempty"`
	DestinationLinkName      string                    `json:"destinationLinkName,omitempty"`
	ReleaseTime              time.Time                 `json:"releaseTime,omitempty"`
	StopPrice                float64                   `json:"stopPrice,omitempty"`
	StopPriceLinkBasis       *StopPriceLinkBasis       `json:"stopPriceLinkBasis,omitempty"`
	StopPriceLinkType        *StopPriceLinkType        `json:"stopPriceLinkType,omitempty"`
	StopPriceOffset          float64                   `json:"stopPriceOffset,omitempty"`
	StopType                 *StopType                 `json:"stopType,omitempty"`
	PriceLinkBasis           *PriceLinkBasis           `json:"priceLinkBasis,omitempty"`
	PriceLinkType            *PriceLinkType            `json:"priceLinkType,omitempty"`
	Price                    float64                   `json:"price,omitempty"`
	TaxLotMethod             *TaxLotMethod             `json:"taxLotMethod,omitempty"`
	OrderLegCollection       []OrderLegCollection      `json:"orderLegCollection,omitempty"`
	ActivationPrice          float64                   `json:"activationPrice,omitempty"`
	SpecialInstruction       *SpecialInstruction       `json:"specialInstruction,omitempty"`
	OrderStrategyType        *OrderStrategyType        `json:"orderStrategyType,omitempty"`
	OrderId                  int64                     `json:"orderId,omitempty"`
	Cancelable               bool                      `json:"cancelable,omitempty"`
	Editable                 bool                      `json:"editable,omitempty"`
	Status                   *Status                   `json:"status,omitempty"`
	EnteredTime              time.Time                 `json:"enteredTime,omitempty"`
	CloseTime                time.Time                 `json:"closeTime,omitempty"`
	Tag                      string                    `json:"tag,omitempty"`
	AccountNumber            int64                     `json:"accountNumber,omitempty"`
	OrderActivityCollection  []OrderActivity           `json:"orderActivityCollection,omitempty"`
	ReplacingOrderCollection []Order                   `json:"replacingOrderCollection,omitempty"`
	ChildOrderStrategies     []Order                   `json:"childOrderStrategies,omitempty"`
	StatusDescription        string                    `json:"statusDescription,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderActivity struct {
	ActivityType           string         `json:"activityType,omitempty"`
	ExecutionType          string         `json:"executionType,omitempty"`
	Quantity               float64        `json:"quantity,omitempty"`
	OrderRemainingQuantity float64        `json:"orderRemainingQuantity,omitempty"`
	ExecutionLegs          []ExecutionLeg `json:"executionLegs,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderBalance struct {
	OrderValue             float64 `json:"orderValue,omitempty"`
	ProjectedAvailableFund float64 `json:"projectedAvailableFund,omitempty"`
	ProjectedBuyingPower   float64 `json:"projectedBuyingPower,omitempty"`
	ProjectedCommission    float64 `json:"projectedCommission,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderLeg struct {
	AskPrice            float64      `json:"askPrice,omitempty"`
	BidPrice            float64      `json:"bidPrice,omitempty"`
	LastPrice           float64      `json:"lastPrice,omitempty"`
	MarkPrice           float64      `json:"markPrice,omitempty"`
	ProjectedCommission float64      `json:"projectedCommission,omitempty"`
	Quantity            float64      `json:"quantity,omitempty"`
	FinalSymbol         string       `json:"finalSymbol,omitempty"`
	LegId               float64      `json:"legId,omitempty"`
	AssetType           *AssetType   `json:"assetType,omitempty"`
	Instruction         *Instruction `json:"instruction,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderLegCollection struct {
	OrderLegType   string              `json:"orderLegType,omitempty"`
	LegId          int64               `json:"legId,omitempty"`
	Instrument     *AccountsInstrument `json:"instrument,omitempty"`
	Instruction    *Instruction        `json:"instruction,omitempty"`
	PositionEffect string              `json:"positionEffect,omitempty"`
	Quantity       float64             `json:"quantity,omitempty"`
	QuantityType   string              `json:"quantityType,omitempty"`
	DivCapGains    string              `json:"divCapGains,omitempty"`
	ToSymbol       string              `json:"toSymbol,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderRequest struct {
	Session                  *Session                  `json:"session,omitempty"`
	Duration                 *Duration                 `json:"duration,omitempty"`
	OrderType                *OrderTypeRequest         `json:"orderType,omitempty"`
	CancelTime               time.Time                 `json:"cancelTime,omitempty"`
	ComplexOrderStrategyType *ComplexOrderStrategyType `json:"complexOrderStrategyType,omitempty"`
	Quantity                 float64                   `json:"quantity,omitempty"`
	FilledQuantity           float64                   `json:"filledQuantity,omitempty"`
	RemainingQuantity        float64                   `json:"remainingQuantity,omitempty"`
	DestinationLinkName      string                    `json:"destinationLinkName,omitempty"`
	ReleaseTime              time.Time                 `json:"releaseTime,omitempty"`
	StopPrice                float64                   `json:"stopPrice,omitempty"`
	StopPriceLinkBasis       *StopPriceLinkBasis       `json:"stopPriceLinkBasis,omitempty"`
	StopPriceLinkType        *StopPriceLinkType        `json:"stopPriceLinkType,omitempty"`
	StopPriceOffset          float64                   `json:"stopPriceOffset,omitempty"`
	StopType                 *StopType                 `json:"stopType,omitempty"`
	PriceLinkBasis           *PriceLinkBasis           `json:"priceLinkBasis,omitempty"`
	PriceLinkType            *PriceLinkType            `json:"priceLinkType,omitempty"`
	Price                    float64                   `json:"price,omitempty"`
	TaxLotMethod             *TaxLotMethod             `json:"taxLotMethod,omitempty"`
	OrderLegCollection       []OrderLegCollection      `json:"orderLegCollection,omitempty"`
	ActivationPrice          float64                   `json:"activationPrice,omitempty"`
	SpecialInstruction       *SpecialInstruction       `json:"specialInstruction,omitempty"`
	OrderStrategyType        *OrderStrategyType        `json:"orderStrategyType,omitempty"`
	OrderId                  int64                     `json:"orderId,omitempty"`
	Cancelable               bool                      `json:"cancelable,omitempty"`
	Editable                 bool                      `json:"editable,omitempty"`
	Status                   *Status                   `json:"status,omitempty"`
	EnteredTime              time.Time                 `json:"enteredTime,omitempty"`
	CloseTime                time.Time                 `json:"closeTime,omitempty"`
	AccountNumber            int64                     `json:"accountNumber,omitempty"`
	OrderActivityCollection  []OrderActivity           `json:"orderActivityCollection,omitempty"`
	ReplacingOrderCollection []OrderRequest            `json:"replacingOrderCollection,omitempty"`
	ChildOrderStrategies     []OrderRequest            `json:"childOrderStrategies,omitempty"`
	StatusDescription        string                    `json:"statusDescription,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderStrategy struct {
	AccountNumber          string                    `json:"accountNumber,omitempty"`
	AdvancedOrderType      string                    `json:"advancedOrderType,omitempty"`
	CloseTime              time.Time                 `json:"closeTime,omitempty"`
	EnteredTime            time.Time                 `json:"enteredTime,omitempty"`
	OrderBalance           *OrderBalance             `json:"orderBalance,omitempty"`
	OrderStrategyType      *OrderStrategyType        `json:"orderStrategyType,omitempty"`
	OrderVersion           float64                   `json:"orderVersion,omitempty"`
	Session                *Session                  `json:"session,omitempty"`
	Status                 *ApiOrderStatus           `json:"status,omitempty"`
	AllOrNone              bool                      `json:"allOrNone,omitempty"`
	Discretionary          bool                      `json:"discretionary,omitempty"`
	Duration               *Duration                 `json:"duration,omitempty"`
	FilledQuantity         float64                   `json:"filledQuantity,omitempty"`
	OrderType              *OrderType                `json:"orderType,omitempty"`
	OrderValue             float64                   `json:"orderValue,omitempty"`
	Price                  float64                   `json:"price,omitempty"`
	Quantity               float64                   `json:"quantity,omitempty"`
	RemainingQuantity      float64                   `json:"remainingQuantity,omitempty"`
	SellNonMarginableFirst bool                      `json:"sellNonMarginableFirst,omitempty"`
	SettlementInstruction  *SettlementInstruction    `json:"settlementInstruction,omitempty"`
	Strategy               *ComplexOrderStrategyType `json:"strategy,omitempty"`
	AmountIndicator        *AmountIndicator          `json:"amountIndicator,omitempty"`
	OrderLegs              []OrderLeg                `json:"orderLegs,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderStrategyType string

// List of orderStrategyType
const (
	SINGLE_OrderStrategyType       OrderStrategyType = "SINGLE"
	CANCEL_OrderStrategyType       OrderStrategyType = "CANCEL"
	RECALL_OrderStrategyType       OrderStrategyType = "RECALL"
	PAIR_OrderStrategyType         OrderStrategyType = "PAIR"
	FLATTEN_OrderStrategyType      OrderStrategyType = "FLATTEN"
	TWO_DAY_SWAP_OrderStrategyType OrderStrategyType = "TWO_DAY_SWAP"
	BLAST_ALL_OrderStrategyType    OrderStrategyType = "BLAST_ALL"
	OCO_OrderStrategyType          OrderStrategyType = "OCO"
	TRIGGER_OrderStrategyType      OrderStrategyType = "TRIGGER"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderType string

// List of orderType
const (
	MARKET_OrderType              OrderType = "MARKET"
	LIMIT_OrderType               OrderType = "LIMIT"
	STOP_OrderType                OrderType = "STOP"
	STOP_LIMIT_OrderType          OrderType = "STOP_LIMIT"
	TRAILING_STOP_OrderType       OrderType = "TRAILING_STOP"
	CABINET_OrderType             OrderType = "CABINET"
	NON_MARKETABLE_OrderType      OrderType = "NON_MARKETABLE"
	MARKET_ON_CLOSE_OrderType     OrderType = "MARKET_ON_CLOSE"
	EXERCISE_OrderType            OrderType = "EXERCISE"
	TRAILING_STOP_LIMIT_OrderType OrderType = "TRAILING_STOP_LIMIT"
	NET_DEBIT_OrderType           OrderType = "NET_DEBIT"
	NET_CREDIT_OrderType          OrderType = "NET_CREDIT"
	NET_ZERO_OrderType            OrderType = "NET_ZERO"
	LIMIT_ON_CLOSE_OrderType      OrderType = "LIMIT_ON_CLOSE"
	UNKNOWN_OrderType             OrderType = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// OrderTypeRequest : Same as orderType, but does not have UNKNOWN since this type is not allowed as an input
type OrderTypeRequest string

// List of orderTypeRequest
const (
	MARKET_OrderTypeRequest              OrderTypeRequest = "MARKET"
	LIMIT_OrderTypeRequest               OrderTypeRequest = "LIMIT"
	STOP_OrderTypeRequest                OrderTypeRequest = "STOP"
	STOP_LIMIT_OrderTypeRequest          OrderTypeRequest = "STOP_LIMIT"
	TRAILING_STOP_OrderTypeRequest       OrderTypeRequest = "TRAILING_STOP"
	CABINET_OrderTypeRequest             OrderTypeRequest = "CABINET"
	NON_MARKETABLE_OrderTypeRequest      OrderTypeRequest = "NON_MARKETABLE"
	MARKET_ON_CLOSE_OrderTypeRequest     OrderTypeRequest = "MARKET_ON_CLOSE"
	EXERCISE_OrderTypeRequest            OrderTypeRequest = "EXERCISE"
	TRAILING_STOP_LIMIT_OrderTypeRequest OrderTypeRequest = "TRAILING_STOP_LIMIT"
	NET_DEBIT_OrderTypeRequest           OrderTypeRequest = "NET_DEBIT"
	NET_CREDIT_OrderTypeRequest          OrderTypeRequest = "NET_CREDIT"
	NET_ZERO_OrderTypeRequest            OrderTypeRequest = "NET_ZERO"
	LIMIT_ON_CLOSE_OrderTypeRequest      OrderTypeRequest = "LIMIT_ON_CLOSE"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderValidationDetail struct {
	ValidationRuleName string         `json:"validationRuleName,omitempty"`
	Message            string         `json:"message,omitempty"`
	ActivityMessage    string         `json:"activityMessage,omitempty"`
	OriginalSeverity   *ApiRuleAction `json:"originalSeverity,omitempty"`
	OverrideName       string         `json:"overrideName,omitempty"`
	OverrideSeverity   *ApiRuleAction `json:"overrideSeverity,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderValidationResult struct {
	Alerts  []OrderValidationDetail `json:"alerts,omitempty"`
	Accepts []OrderValidationDetail `json:"accepts,omitempty"`
	Rejects []OrderValidationDetail `json:"rejects,omitempty"`
	Reviews []OrderValidationDetail `json:"reviews,omitempty"`
	Warns   []OrderValidationDetail `json:"warns,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Position struct {
	ShortQuantity                  float64             `json:"shortQuantity,omitempty"`
	AveragePrice                   float64             `json:"averagePrice,omitempty"`
	CurrentDayProfitLoss           float64             `json:"currentDayProfitLoss,omitempty"`
	CurrentDayProfitLossPercentage float64             `json:"currentDayProfitLossPercentage,omitempty"`
	LongQuantity                   float64             `json:"longQuantity,omitempty"`
	SettledLongQuantity            float64             `json:"settledLongQuantity,omitempty"`
	SettledShortQuantity           float64             `json:"settledShortQuantity,omitempty"`
	AgedQuantity                   float64             `json:"agedQuantity,omitempty"`
	Instrument                     *AccountsInstrument `json:"instrument,omitempty"`
	MarketValue                    float64             `json:"marketValue,omitempty"`
	MaintenanceRequirement         float64             `json:"maintenanceRequirement,omitempty"`
	AverageLongPrice               float64             `json:"averageLongPrice,omitempty"`
	AverageShortPrice              float64             `json:"averageShortPrice,omitempty"`
	TaxLotAverageLongPrice         float64             `json:"taxLotAverageLongPrice,omitempty"`
	TaxLotAverageShortPrice        float64             `json:"taxLotAverageShortPrice,omitempty"`
	LongOpenProfitLoss             float64             `json:"longOpenProfitLoss,omitempty"`
	ShortOpenProfitLoss            float64             `json:"shortOpenProfitLoss,omitempty"`
	PreviousSessionLongQuantity    float64             `json:"previousSessionLongQuantity,omitempty"`
	PreviousSessionShortQuantity   float64             `json:"previousSessionShortQuantity,omitempty"`
	CurrentDayCost                 float64             `json:"currentDayCost,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type PreviewOrder struct {
	OrderId               int64                  `json:"orderId,omitempty"`
	OrderStrategy         *OrderStrategy         `json:"orderStrategy,omitempty"`
	OrderValidationResult *OrderValidationResult `json:"orderValidationResult,omitempty"`
	CommissionAndFee      *CommissionAndFee      `json:"commissionAndFee,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type PriceLinkBasis string

// List of priceLinkBasis
const (
	MANUAL_PriceLinkBasis  PriceLinkBasis = "MANUAL"
	BASE_PriceLinkBasis    PriceLinkBasis = "BASE"
	TRIGGER_PriceLinkBasis PriceLinkBasis = "TRIGGER"
	LAST_PriceLinkBasis    PriceLinkBasis = "LAST"
	BID_PriceLinkBasis     PriceLinkBasis = "BID"
	ASK_PriceLinkBasis     PriceLinkBasis = "ASK"
	ASK_BID_PriceLinkBasis PriceLinkBasis = "ASK_BID"
	MARK_PriceLinkBasis    PriceLinkBasis = "MARK"
	AVERAGE_PriceLinkBasis PriceLinkBasis = "AVERAGE"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type PriceLinkType string

// List of priceLinkType
const (
	VALUE_PriceLinkType   PriceLinkType = "VALUE"
	PERCENT_PriceLinkType PriceLinkType = "PERCENT"
	TICK_PriceLinkType    PriceLinkType = "TICK"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Product struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
	Type_        string  `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type RequestedDestination string

// List of requestedDestination
const (
	INET_RequestedDestination     RequestedDestination = "INET"
	ECN_ARCA_RequestedDestination RequestedDestination = "ECN_ARCA"
	CBOE_RequestedDestination     RequestedDestination = "CBOE"
	AMEX_RequestedDestination     RequestedDestination = "AMEX"
	PHLX_RequestedDestination     RequestedDestination = "PHLX"
	ISE_RequestedDestination      RequestedDestination = "ISE"
	BOX_RequestedDestination      RequestedDestination = "BOX"
	NYSE_RequestedDestination     RequestedDestination = "NYSE"
	NASDAQ_RequestedDestination   RequestedDestination = "NASDAQ"
	BATS_RequestedDestination     RequestedDestination = "BATS"
	C2_RequestedDestination       RequestedDestination = "C2"
	AUTO_RequestedDestination     RequestedDestination = "AUTO"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type SecuritiesAccount struct {
	MarginAccount
	CashAccount
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type SecuritiesAccountBase struct {
	Type_                   string     `json:"type,omitempty"`
	AccountNumber           string     `json:"accountNumber,omitempty"`
	RoundTrips              int32      `json:"roundTrips,omitempty"`
	IsDayTrader             bool       `json:"isDayTrader,omitempty"`
	IsClosingOnlyRestricted bool       `json:"isClosingOnlyRestricted,omitempty"`
	PfcbFlag                bool       `json:"pfcbFlag,omitempty"`
	Positions               []Position `json:"positions,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ServiceError struct {
	Message string   `json:"message,omitempty"`
	Errors  []string `json:"errors,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Session string

// List of session
const (
	NORMAL_Session   Session = "NORMAL"
	AM_Session       Session = "AM"
	PM_Session       Session = "PM"
	SEAMLESS_Session Session = "SEAMLESS"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type SettlementInstruction string

// List of settlementInstruction
const (
	REGULAR_SettlementInstruction  SettlementInstruction = "REGULAR"
	CASH_SettlementInstruction     SettlementInstruction = "CASH"
	NEXT_DAY_SettlementInstruction SettlementInstruction = "NEXT_DAY"
	UNKNOWN_SettlementInstruction  SettlementInstruction = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type SpecialInstruction string

// List of specialInstruction
const (
	ALL_OR_NONE_SpecialInstruction               SpecialInstruction = "ALL_OR_NONE"
	DO_NOT_REDUCE_SpecialInstruction             SpecialInstruction = "DO_NOT_REDUCE"
	ALL_OR_NONE_DO_NOT_REDUCE_SpecialInstruction SpecialInstruction = "ALL_OR_NONE_DO_NOT_REDUCE"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Status string

// List of status
const (
	AWAITING_PARENT_ORDER_Status   Status = "AWAITING_PARENT_ORDER"
	AWAITING_CONDITION_Status      Status = "AWAITING_CONDITION"
	AWAITING_STOP_CONDITION_Status Status = "AWAITING_STOP_CONDITION"
	AWAITING_MANUAL_REVIEW_Status  Status = "AWAITING_MANUAL_REVIEW"
	ACCEPTED_Status                Status = "ACCEPTED"
	AWAITING_UR_OUT_Status         Status = "AWAITING_UR_OUT"
	PENDING_ACTIVATION_Status      Status = "PENDING_ACTIVATION"
	QUEUED_Status                  Status = "QUEUED"
	WORKING_Status                 Status = "WORKING"
	REJECTED_Status                Status = "REJECTED"
	PENDING_CANCEL_Status          Status = "PENDING_CANCEL"
	CANCELED_Status                Status = "CANCELED"
	PENDING_REPLACE_Status         Status = "PENDING_REPLACE"
	REPLACED_Status                Status = "REPLACED"
	FILLED_Status                  Status = "FILLED"
	EXPIRED_Status                 Status = "EXPIRED"
	NEW_Status                     Status = "NEW"
	AWAITING_RELEASE_TIME_Status   Status = "AWAITING_RELEASE_TIME"
	PENDING_ACKNOWLEDGEMENT_Status Status = "PENDING_ACKNOWLEDGEMENT"
	PENDING_RECALL_Status          Status = "PENDING_RECALL"
	UNKNOWN_Status                 Status = "UNKNOWN"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type StopPriceLinkBasis string

// List of stopPriceLinkBasis
const (
	MANUAL_StopPriceLinkBasis  StopPriceLinkBasis = "MANUAL"
	BASE_StopPriceLinkBasis    StopPriceLinkBasis = "BASE"
	TRIGGER_StopPriceLinkBasis StopPriceLinkBasis = "TRIGGER"
	LAST_StopPriceLinkBasis    StopPriceLinkBasis = "LAST"
	BID_StopPriceLinkBasis     StopPriceLinkBasis = "BID"
	ASK_StopPriceLinkBasis     StopPriceLinkBasis = "ASK"
	ASK_BID_StopPriceLinkBasis StopPriceLinkBasis = "ASK_BID"
	MARK_StopPriceLinkBasis    StopPriceLinkBasis = "MARK"
	AVERAGE_StopPriceLinkBasis StopPriceLinkBasis = "AVERAGE"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type StopPriceLinkType string

// List of stopPriceLinkType
const (
	VALUE_StopPriceLinkType   StopPriceLinkType = "VALUE"
	PERCENT_StopPriceLinkType StopPriceLinkType = "PERCENT"
	TICK_StopPriceLinkType    StopPriceLinkType = "TICK"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type StopType string

// List of stopType
const (
	STANDARD_StopType StopType = "STANDARD"
	BID_StopType      StopType = "BID"
	ASK_StopType      StopType = "ASK"
	LAST_StopType     StopType = "LAST"
	MARK_StopType     StopType = "MARK"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type StreamerInfo struct {
	StreamerSocketUrl      string `json:"streamerSocketUrl,omitempty"`
	SchwabClientCustomerId string `json:"schwabClientCustomerId,omitempty"`
	SchwabClientCorrelId   string `json:"schwabClientCorrelId,omitempty"`
	SchwabClientChannel    string `json:"schwabClientChannel,omitempty"`
	SchwabClientFunctionId string `json:"schwabClientFunctionId,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TaxLotMethod string

// List of taxLotMethod
const (
	FIFO_TaxLotMethod           TaxLotMethod = "FIFO"
	LIFO_TaxLotMethod           TaxLotMethod = "LIFO"
	HIGH_COST_TaxLotMethod      TaxLotMethod = "HIGH_COST"
	LOW_COST_TaxLotMethod       TaxLotMethod = "LOW_COST"
	AVERAGE_COST_TaxLotMethod   TaxLotMethod = "AVERAGE_COST"
	SPECIFIC_LOT_TaxLotMethod   TaxLotMethod = "SPECIFIC_LOT"
	LOSS_HARVESTER_TaxLotMethod TaxLotMethod = "LOSS_HARVESTER"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Transaction struct {
	ActivityId     int64            `json:"activityId,omitempty"`
	Time           time.Time        `json:"time,omitempty"`
	User           *UserDetails     `json:"user,omitempty"`
	Description    string           `json:"description,omitempty"`
	AccountNumber  string           `json:"accountNumber,omitempty"`
	Type_          *TransactionType `json:"type,omitempty"`
	Status         string           `json:"status,omitempty"`
	SubAccount     string           `json:"subAccount,omitempty"`
	TradeDate      time.Time        `json:"tradeDate,omitempty"`
	SettlementDate time.Time        `json:"settlementDate,omitempty"`
	PositionId     int64            `json:"positionId,omitempty"`
	OrderId        int64            `json:"orderId,omitempty"`
	NetAmount      float64          `json:"netAmount,omitempty"`
	ActivityType   string           `json:"activityType,omitempty"`
	TransferItems  []TransferItem   `json:"transferItems,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionApiOptionDeliverable struct {
	RootSymbol        string                 `json:"rootSymbol,omitempty"`
	StrikePercent     int64                  `json:"strikePercent,omitempty"`
	DeliverableNumber int64                  `json:"deliverableNumber,omitempty"`
	DeliverableUnits  float64                `json:"deliverableUnits,omitempty"`
	Deliverable       *TransactionInstrument `json:"deliverable,omitempty"`
	AssetType         *AssetType             `json:"assetType,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionBaseInstrument struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionCashEquivalent struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
	Type_        string  `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionEquity struct {
	AssetType    string  `json:"assetType"`
	Cusip        string  `json:"cusip,omitempty"`
	Symbol       string  `json:"symbol,omitempty"`
	Description  string  `json:"description,omitempty"`
	InstrumentId int64   `json:"instrumentId,omitempty"`
	NetChange    float64 `json:"netChange,omitempty"`
	Type_        string  `json:"type,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionFixedIncome struct {
	AssetType    string    `json:"assetType"`
	Cusip        string    `json:"cusip,omitempty"`
	Symbol       string    `json:"symbol,omitempty"`
	Description  string    `json:"description,omitempty"`
	InstrumentId int64     `json:"instrumentId,omitempty"`
	NetChange    float64   `json:"netChange,omitempty"`
	Type_        string    `json:"type,omitempty"`
	MaturityDate time.Time `json:"maturityDate,omitempty"`
	Factor       float64   `json:"factor,omitempty"`
	Multiplier   float64   `json:"multiplier,omitempty"`
	VariableRate float64   `json:"variableRate,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionInstrument struct {
	TransactionCashEquivalent
	CollectiveInvestment
	Currency
	TransactionEquity
	TransactionFixedIncome
	Forex
	Future
	Index
	TransactionMutualFund
	TransactionOption
	Product
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionMutualFund struct {
	AssetType            string    `json:"assetType"`
	Cusip                string    `json:"cusip,omitempty"`
	Symbol               string    `json:"symbol,omitempty"`
	Description          string    `json:"description,omitempty"`
	InstrumentId         int64     `json:"instrumentId,omitempty"`
	NetChange            float64   `json:"netChange,omitempty"`
	FundFamilyName       string    `json:"fundFamilyName,omitempty"`
	FundFamilySymbol     string    `json:"fundFamilySymbol,omitempty"`
	FundGroup            string    `json:"fundGroup,omitempty"`
	Type_                string    `json:"type,omitempty"`
	ExchangeCutoffTime   time.Time `json:"exchangeCutoffTime,omitempty"`
	PurchaseCutoffTime   time.Time `json:"purchaseCutoffTime,omitempty"`
	RedemptionCutoffTime time.Time `json:"redemptionCutoffTime,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionOption struct {
	AssetType               string                            `json:"assetType"`
	Cusip                   string                            `json:"cusip,omitempty"`
	Symbol                  string                            `json:"symbol,omitempty"`
	Description             string                            `json:"description,omitempty"`
	InstrumentId            int64                             `json:"instrumentId,omitempty"`
	NetChange               float64                           `json:"netChange,omitempty"`
	ExpirationDate          time.Time                         `json:"expirationDate,omitempty"`
	OptionDeliverables      []TransactionApiOptionDeliverable `json:"optionDeliverables,omitempty"`
	OptionPremiumMultiplier int64                             `json:"optionPremiumMultiplier,omitempty"`
	PutCall                 string                            `json:"putCall,omitempty"`
	StrikePrice             float64                           `json:"strikePrice,omitempty"`
	Type_                   string                            `json:"type,omitempty"`
	UnderlyingSymbol        string                            `json:"underlyingSymbol,omitempty"`
	UnderlyingCusip         string                            `json:"underlyingCusip,omitempty"`
	Deliverable             *TransactionInstrument            `json:"deliverable,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransactionType string

// List of TransactionType
const (
	TRADE_TransactionType                TransactionType = "TRADE"
	RECEIVE_AND_DELIVER_TransactionType  TransactionType = "RECEIVE_AND_DELIVER"
	DIVIDEND_OR_INTEREST_TransactionType TransactionType = "DIVIDEND_OR_INTEREST"
	ACH_RECEIPT_TransactionType          TransactionType = "ACH_RECEIPT"
	ACH_DISBURSEMENT_TransactionType     TransactionType = "ACH_DISBURSEMENT"
	CASH_RECEIPT_TransactionType         TransactionType = "CASH_RECEIPT"
	CASH_DISBURSEMENT_TransactionType    TransactionType = "CASH_DISBURSEMENT"
	ELECTRONIC_FUND_TransactionType      TransactionType = "ELECTRONIC_FUND"
	WIRE_OUT_TransactionType             TransactionType = "WIRE_OUT"
	WIRE_IN_TransactionType              TransactionType = "WIRE_IN"
	JOURNAL_TransactionType              TransactionType = "JOURNAL"
	MEMORANDUM_TransactionType           TransactionType = "MEMORANDUM"
	MARGIN_CALL_TransactionType          TransactionType = "MARGIN_CALL"
	MONEY_MARKET_TransactionType         TransactionType = "MONEY_MARKET"
	SMA_ADJUSTMENT_TransactionType       TransactionType = "SMA_ADJUSTMENT"
)

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type TransferItem struct {
	Instrument     *TransactionInstrument `json:"instrument,omitempty"`
	Amount         float64                `json:"amount,omitempty"`
	Cost           float64                `json:"cost,omitempty"`
	Price          float64                `json:"price,omitempty"`
	FeeType        string                 `json:"feeType,omitempty"`
	PositionEffect string                 `json:"positionEffect,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type UserDetails struct {
	CdDomainId     string `json:"cdDomainId,omitempty"`
	Login          string `json:"login,omitempty"`
	Type_          string `json:"type,omitempty"`
	UserId         int64  `json:"userId,omitempty"`
	SystemUserName string `json:"systemUserName,omitempty"`
	FirstName      string `json:"firstName,omitempty"`
	LastName       string `json:"lastName,omitempty"`
	BrokerRepCode  string `json:"brokerRepCode,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type UserPreference struct {
	Accounts     []UserPreferenceAccount `json:"accounts,omitempty"`
	StreamerInfo []StreamerInfo          `json:"streamerInfo,omitempty"`
	Offers       []Offer                 `json:"offers,omitempty"`
}

/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type UserPreferenceAccount struct {
	AccountNumber  string `json:"accountNumber,omitempty"`
	PrimaryAccount bool   `json:"primaryAccount,omitempty"`
	Type_          string `json:"type,omitempty"`
	NickName       string `json:"nickName,omitempty"`
	// Green | Blue
	AccountColor       string `json:"accountColor,omitempty"`
	DisplayAcctId      string `json:"displayAcctId,omitempty"`
	AutoPositionEffect bool   `json:"autoPositionEffect,omitempty"`
}
