package models

import (
	"time"
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// AssetMainType : Instrument's asset type
type AssetMainType string

// List of AssetMainType
const (
	BOND_AssetMainType          AssetMainType = "BOND"
	EQUITY_AssetMainType        AssetMainType = "EQUITY"
	FOREX_AssetMainType         AssetMainType = "FOREX"
	FUTURE_AssetMainType        AssetMainType = "FUTURE"
	FUTURE_OPTION_AssetMainType AssetMainType = "FUTURE_OPTION"
	INDEX_AssetMainType         AssetMainType = "INDEX"
	MUTUAL_FUND_AssetMainType   AssetMainType = "MUTUAL_FUND"
	OPTION_AssetMainType        AssetMainType = "OPTION"
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Bond struct {
	Cusip          string  `json:"cusip,omitempty"`
	Symbol         string  `json:"symbol,omitempty"`
	Description    string  `json:"description,omitempty"`
	Exchange       string  `json:"exchange,omitempty"`
	AssetType      string  `json:"assetType,omitempty"`
	BondFactor     string  `json:"bondFactor,omitempty"`
	BondMultiplier string  `json:"bondMultiplier,omitempty"`
	BondPrice      float64 `json:"bondPrice,omitempty"`
	Type_          string  `json:"type,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Candle struct {
	Close           float64 `json:"close,omitempty"`
	Datetime        int64   `json:"datetime,omitempty"`
	DatetimeISO8601 string  `json:"datetimeISO8601,omitempty"`
	High            float64 `json:"high,omitempty"`
	Low             float64 `json:"low,omitempty"`
	Open            float64 `json:"open,omitempty"`
	Volume          int64   `json:"volume,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type CandleList struct {
	Candles                  []Candle `json:"candles,omitempty"`
	Empty                    bool     `json:"empty,omitempty"`
	PreviousClose            float64  `json:"previousClose,omitempty"`
	PreviousCloseDate        int64    `json:"previousCloseDate,omitempty"`
	PreviousCloseDateISO8601 string   `json:"previousCloseDateISO8601,omitempty"`
	Symbol                   string   `json:"symbol,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// ContractType : Indicates call or put
type ContractType string

// List of ContractType
const (
	P_ContractType ContractType = "P"
	C_ContractType ContractType = "C"
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// DivFreq : Dividend frequency 1 – once a year or annually 2 – 2x a year or semi-annualy 3 - 3x a year (ex. ARCO, EBRPF) 4 – 4x a year or quarterly 6 - 6x per yr or every other month 11 – 11x a year (ex. FBND, FCOR) 12 – 12x a year or monthly
type DivFreq int32

// List of DivFreq
const (
	DivFreq__1   DivFreq = 1
	DivFreq__2   DivFreq = 2
	DivFreq__3   DivFreq = 3
	DivFreq__4   DivFreq = 4
	DivFreq__5   DivFreq = 6
	DivFreq__11  DivFreq = 11
	DivFreq__12  DivFreq = 12
	NULL_DivFreq DivFreq = 0
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// EquityAssetSubType : Asset Sub Type (only there if applicable)
type EquityAssetSubType string

// List of EquityAssetSubType
const (
	COE_EquityAssetSubType  EquityAssetSubType = "COE"
	PRF_EquityAssetSubType  EquityAssetSubType = "PRF"
	ADR_EquityAssetSubType  EquityAssetSubType = "ADR"
	GDR_EquityAssetSubType  EquityAssetSubType = "GDR"
	CEF_EquityAssetSubType  EquityAssetSubType = "CEF"
	ETF_EquityAssetSubType  EquityAssetSubType = "ETF"
	ETN_EquityAssetSubType  EquityAssetSubType = "ETN"
	UIT_EquityAssetSubType  EquityAssetSubType = "UIT"
	WAR_EquityAssetSubType  EquityAssetSubType = "WAR"
	RGT_EquityAssetSubType  EquityAssetSubType = "RGT"
	NULL_EquityAssetSubType EquityAssetSubType = ""
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of Equity security
type EquityResponse struct {
	AssetMainType *AssetMainType      `json:"assetMainType,omitempty"`
	AssetSubType  *EquityAssetSubType `json:"assetSubType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime    bool             `json:"realtime,omitempty"`
	QuoteType   *QuoteType       `json:"quoteType,omitempty"`
	Extended    *ExtendedMarket  `json:"extended,omitempty"`
	Fundamental *Fundamental     `json:"fundamental,omitempty"`
	Quote       *QuoteEquity     `json:"quote,omitempty"`
	Reference   *ReferenceEquity `json:"reference,omitempty"`
	Regular     *RegularMarket   `json:"regular,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ModelError struct {
	// Unique error id.
	Id string `json:"id,omitempty"`
	// The HTTP status code .
	Status string `json:"status,omitempty"`
	// Short error description.
	Title string `json:"title,omitempty"`
	// Detailed error description.
	Detail string       `json:"detail,omitempty"`
	Source *ErrorSource `json:"source,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ErrorResponse struct {
	Errors []ModelError `json:"errors,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Who is responsible for triggering these errors.
type ErrorSource struct {
	// list of attributes which lead to this error message.
	Pointer []string `json:"pointer,omitempty"`
	// parameter name which lead to this error message.
	Parameter string `json:"parameter,omitempty"`
	// header name which lead to this error message.
	Header string `json:"header,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// ExerciseType : option contract exercise type America or European
type ExerciseType string

// List of ExerciseType
const (
	A_ExerciseType ExerciseType = "A"
	E_ExerciseType ExerciseType = "E"
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// expiration type
type Expiration struct {
	DaysToExpiration int32           `json:"daysToExpiration,omitempty"`
	Expiration       string          `json:"expiration,omitempty"`
	ExpirationType   *ExpirationType `json:"expirationType,omitempty"`
	Standard         bool            `json:"standard,omitempty"`
	SettlementType   *SettlementType `json:"settlementType,omitempty"`
	OptionRoots      string          `json:"optionRoots,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type ExpirationChain struct {
	Status         string       `json:"status,omitempty"`
	ExpirationList []Expiration `json:"expirationList,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// ExpirationType : M for End Of Month Expiration Calendar Cycle. (To match the last business day of the month), Q for Quarterly expirations (last business day of the quarter month MAR/JUN/SEP/DEC), W for Weekly expiration (also called Friday Short Term Expirations) and S for Expires 3rd Friday of the month (also known as regular options).
type ExpirationType string

// List of ExpirationType
const (
	M_ExpirationType ExpirationType = "M"
	Q_ExpirationType ExpirationType = "Q"
	S_ExpirationType ExpirationType = "S"
	W_ExpirationType ExpirationType = "W"
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data for extended hours
type ExtendedMarket struct {
	// Extended market ask price
	AskPrice float64 `json:"askPrice,omitempty"`
	// Extended market ask size
	AskSize int32 `json:"askSize,omitempty"`
	// Extended market bid price
	BidPrice float64 `json:"bidPrice,omitempty"`
	// Extended market bid size
	BidSize int32 `json:"bidSize,omitempty"`
	// Extended market last price
	LastPrice float64 `json:"lastPrice,omitempty"`
	// Regular market last size
	LastSize int32 `json:"lastSize,omitempty"`
	// mark price
	Mark float64 `json:"mark,omitempty"`
	// Extended market quote time in milliseconds since Epoch
	QuoteTime int64 `json:"quoteTime,omitempty"`
	// Total volume
	TotalVolume float64 `json:"totalVolume,omitempty"`
	// Extended market trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of Forex security
type ForexResponse struct {
	AssetMainType *AssetMainType `json:"assetMainType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime  bool            `json:"realtime,omitempty"`
	Quote     *QuoteForex     `json:"quote,omitempty"`
	Reference *ReferenceForex `json:"reference,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// FundStrategy : FundStrategy \"A\" - Active \"L\" - Leveraged \"P\" - Passive \"Q\" - Quantitative \"S\" - Short
type FundStrategy string

// List of FundStrategy
const (
	A_FundStrategy    FundStrategy = "A"
	L_FundStrategy    FundStrategy = "L"
	P_FundStrategy    FundStrategy = "P"
	Q_FundStrategy    FundStrategy = "Q"
	S_FundStrategy    FundStrategy = "S"
	NULL_FundStrategy FundStrategy = ""
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Fundamentals of a security
type Fundamental struct {
	// Average 10 day volume
	Avg10DaysVolume float64 `json:"avg10DaysVolume,omitempty"`
	// Average 1 day volume
	Avg1YearVolume float64 `json:"avg1YearVolume,omitempty"`
	// Declaration date in yyyy-mm-ddThh:mm:ssZ
	DeclarationDate time.Time `json:"declarationDate,omitempty"`
	// Dividend Amount
	DivAmount float64 `json:"divAmount,omitempty"`
	// Dividend date in yyyy-mm-ddThh:mm:ssZ
	DivExDate string   `json:"divExDate,omitempty"`
	DivFreq   *DivFreq `json:"divFreq,omitempty"`
	// Dividend Pay Amount
	DivPayAmount float64 `json:"divPayAmount,omitempty"`
	// Dividend pay date in yyyy-mm-ddThh:mm:ssZ
	DivPayDate time.Time `json:"divPayDate,omitempty"`
	// Dividend yield
	DivYield float64 `json:"divYield,omitempty"`
	// Earnings per Share
	Eps float64 `json:"eps,omitempty"`
	// Fund Leverage Factor + > 0 <-
	FundLeverageFactor float64       `json:"fundLeverageFactor,omitempty"`
	FundStrategy       *FundStrategy `json:"fundStrategy,omitempty"`
	// Next Dividend date
	NextDivExDate time.Time `json:"nextDivExDate,omitempty"`
	// Next Dividend pay date
	NextDivPayDate time.Time `json:"nextDivPayDate,omitempty"`
	// P/E Ratio
	PeRatio float64 `json:"peRatio,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type FundamentalInst struct {
	Symbol              string  `json:"symbol,omitempty"`
	High52              float64 `json:"high52,omitempty"`
	Low52               float64 `json:"low52,omitempty"`
	DividendAmount      float64 `json:"dividendAmount,omitempty"`
	DividendYield       float64 `json:"dividendYield,omitempty"`
	DividendDate        string  `json:"dividendDate,omitempty"`
	PeRatio             float64 `json:"peRatio,omitempty"`
	PegRatio            float64 `json:"pegRatio,omitempty"`
	PbRatio             float64 `json:"pbRatio,omitempty"`
	PrRatio             float64 `json:"prRatio,omitempty"`
	PcfRatio            float64 `json:"pcfRatio,omitempty"`
	GrossMarginTTM      float64 `json:"grossMarginTTM,omitempty"`
	GrossMarginMRQ      float64 `json:"grossMarginMRQ,omitempty"`
	NetProfitMarginTTM  float64 `json:"netProfitMarginTTM,omitempty"`
	NetProfitMarginMRQ  float64 `json:"netProfitMarginMRQ,omitempty"`
	OperatingMarginTTM  float64 `json:"operatingMarginTTM,omitempty"`
	OperatingMarginMRQ  float64 `json:"operatingMarginMRQ,omitempty"`
	ReturnOnEquity      float64 `json:"returnOnEquity,omitempty"`
	ReturnOnAssets      float64 `json:"returnOnAssets,omitempty"`
	ReturnOnInvestment  float64 `json:"returnOnInvestment,omitempty"`
	QuickRatio          float64 `json:"quickRatio,omitempty"`
	CurrentRatio        float64 `json:"currentRatio,omitempty"`
	InterestCoverage    float64 `json:"interestCoverage,omitempty"`
	TotalDebtToCapital  float64 `json:"totalDebtToCapital,omitempty"`
	LtDebtToEquity      float64 `json:"ltDebtToEquity,omitempty"`
	TotalDebtToEquity   float64 `json:"totalDebtToEquity,omitempty"`
	EpsTTM              float64 `json:"epsTTM,omitempty"`
	EpsChangePercentTTM float64 `json:"epsChangePercentTTM,omitempty"`
	EpsChangeYear       float64 `json:"epsChangeYear,omitempty"`
	EpsChange           float64 `json:"epsChange,omitempty"`
	RevChangeYear       float64 `json:"revChangeYear,omitempty"`
	RevChangeTTM        float64 `json:"revChangeTTM,omitempty"`
	RevChangeIn         float64 `json:"revChangeIn,omitempty"`
	SharesOutstanding   float64 `json:"sharesOutstanding,omitempty"`
	MarketCapFloat      float64 `json:"marketCapFloat,omitempty"`
	MarketCap           float64 `json:"marketCap,omitempty"`
	BookValuePerShare   float64 `json:"bookValuePerShare,omitempty"`
	ShortIntToFloat     float64 `json:"shortIntToFloat,omitempty"`
	ShortIntDayToCover  float64 `json:"shortIntDayToCover,omitempty"`
	DivGrowthRate3Year  float64 `json:"divGrowthRate3Year,omitempty"`
	DividendPayAmount   float64 `json:"dividendPayAmount,omitempty"`
	DividendPayDate     string  `json:"dividendPayDate,omitempty"`
	Beta                float64 `json:"beta,omitempty"`
	Vol1DayAvg          float64 `json:"vol1DayAvg,omitempty"`
	Vol10DayAvg         float64 `json:"vol10DayAvg,omitempty"`
	Vol3MonthAvg        float64 `json:"vol3MonthAvg,omitempty"`
	Avg10DaysVolume     int64   `json:"avg10DaysVolume,omitempty"`
	Avg1DayVolume       int64   `json:"avg1DayVolume,omitempty"`
	Avg3MonthVolume     int64   `json:"avg3MonthVolume,omitempty"`
	DeclarationDate     string  `json:"declarationDate,omitempty"`
	DividendFreq        int32   `json:"dividendFreq,omitempty"`
	Eps                 float64 `json:"eps,omitempty"`
	CorpactionDate      string  `json:"corpactionDate,omitempty"`
	DtnVolume           int64   `json:"dtnVolume,omitempty"`
	NextDividendPayDate string  `json:"nextDividendPayDate,omitempty"`
	NextDividendDate    string  `json:"nextDividendDate,omitempty"`
	FundLeverageFactor  float64 `json:"fundLeverageFactor,omitempty"`
	FundStrategy        string  `json:"fundStrategy,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of Future Option security
type FutureOptionResponse struct {
	AssetMainType *AssetMainType `json:"assetMainType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime  bool                   `json:"realtime,omitempty"`
	Quote     *QuoteFutureOption     `json:"quote,omitempty"`
	Reference *ReferenceFutureOption `json:"reference,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of Future security
type FutureResponse struct {
	AssetMainType *AssetMainType `json:"assetMainType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime  bool             `json:"realtime,omitempty"`
	Quote     *QuoteFuture     `json:"quote,omitempty"`
	Reference *ReferenceFuture `json:"reference,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Hours struct {
	Date         string                `json:"date,omitempty"`
	MarketType   string                `json:"marketType,omitempty"`
	Exchange     string                `json:"exchange,omitempty"`
	Category     string                `json:"category,omitempty"`
	Product      string                `json:"product,omitempty"`
	ProductName  string                `json:"productName,omitempty"`
	IsOpen       bool                  `json:"isOpen,omitempty"`
	SessionHours map[string][]Interval `json:"sessionHours,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of Index security
type IndexResponse struct {
	AssetMainType *AssetMainType `json:"assetMainType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime  bool            `json:"realtime,omitempty"`
	Quote     *QuoteIndex     `json:"quote,omitempty"`
	Reference *ReferenceIndex `json:"reference,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type InlineResponse200 struct {
	Screeners []Screener `json:"screeners,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type InlineResponse2001 struct {
	Instruments []InstrumentResponse `json:"instruments,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Instrument struct {
	Cusip       string `json:"cusip,omitempty"`
	Symbol      string `json:"symbol,omitempty"`
	Description string `json:"description,omitempty"`
	Exchange    string `json:"exchange,omitempty"`
	AssetType   string `json:"assetType,omitempty"`
	Type_       string `json:"type,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type InstrumentResponse struct {
	Cusip              string           `json:"cusip,omitempty"`
	Symbol             string           `json:"symbol,omitempty"`
	Description        string           `json:"description,omitempty"`
	Exchange           string           `json:"exchange,omitempty"`
	AssetType          string           `json:"assetType,omitempty"`
	BondFactor         string           `json:"bondFactor,omitempty"`
	BondMultiplier     string           `json:"bondMultiplier,omitempty"`
	BondPrice          float64          `json:"bondPrice,omitempty"`
	Fundamental        *FundamentalInst `json:"fundamental,omitempty"`
	InstrumentInfo     *Instrument      `json:"instrumentInfo,omitempty"`
	BondInstrumentInfo *Bond            `json:"bondInstrumentInfo,omitempty"`
	Type_              string           `json:"type,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Interval struct {
	Start string `json:"start,omitempty"`
	End   string `json:"end,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// MutualFundAssetSubType : Asset Sub Type (only there if applicable)
type MutualFundAssetSubType string

// List of MutualFundAssetSubType
const (
	OEF_MutualFundAssetSubType  MutualFundAssetSubType = "OEF"
	CEF_MutualFundAssetSubType  MutualFundAssetSubType = "CEF"
	MMF_MutualFundAssetSubType  MutualFundAssetSubType = "MMF"
	NULL_MutualFundAssetSubType MutualFundAssetSubType = ""
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of MutualFund security
type MutualFundResponse struct {
	AssetMainType *AssetMainType          `json:"assetMainType,omitempty"`
	AssetSubType  *MutualFundAssetSubType `json:"assetSubType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime    bool                 `json:"realtime,omitempty"`
	Fundamental *Fundamental         `json:"fundamental,omitempty"`
	Quote       *QuoteMutualFund     `json:"quote,omitempty"`
	Reference   *ReferenceMutualFund `json:"reference,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OptionChain struct {
	Symbol           string                               `json:"symbol,omitempty"`
	Status           string                               `json:"status,omitempty"`
	Underlying       *Underlying                          `json:"underlying,omitempty"`
	Strategy         string                               `json:"strategy,omitempty"`
	Interval         float64                              `json:"interval,omitempty"`
	IsDelayed        bool                                 `json:"isDelayed,omitempty"`
	IsIndex          bool                                 `json:"isIndex,omitempty"`
	DaysToExpiration float64                              `json:"daysToExpiration,omitempty"`
	InterestRate     float64                              `json:"interestRate,omitempty"`
	UnderlyingPrice  float64                              `json:"underlyingPrice,omitempty"`
	Volatility       float64                              `json:"volatility,omitempty"`
	CallExpDateMap   map[string]map[string]OptionContract `json:"callExpDateMap,omitempty"`
	PutExpDateMap    map[string]map[string]OptionContract `json:"putExpDateMap,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OptionContract struct {
	PutCall                string               `json:"putCall,omitempty"`
	Symbol                 string               `json:"symbol,omitempty"`
	Description            string               `json:"description,omitempty"`
	ExchangeName           string               `json:"exchangeName,omitempty"`
	BidPrice               float64              `json:"bidPrice,omitempty"`
	AskPrice               float64              `json:"askPrice,omitempty"`
	LastPrice              float64              `json:"lastPrice,omitempty"`
	MarkPrice              float64              `json:"markPrice,omitempty"`
	BidSize                int32                `json:"bidSize,omitempty"`
	AskSize                int32                `json:"askSize,omitempty"`
	LastSize               int32                `json:"lastSize,omitempty"`
	HighPrice              float64              `json:"highPrice,omitempty"`
	LowPrice               float64              `json:"lowPrice,omitempty"`
	OpenPrice              float64              `json:"openPrice,omitempty"`
	ClosePrice             float64              `json:"closePrice,omitempty"`
	TotalVolume            int32                `json:"totalVolume,omitempty"`
	TradeDate              float64              `json:"tradeDate,omitempty"`
	QuoteTimeInLong        int32                `json:"quoteTimeInLong,omitempty"`
	TradeTimeInLong        int32                `json:"tradeTimeInLong,omitempty"`
	NetChange              float64              `json:"netChange,omitempty"`
	Volatility             float64              `json:"volatility,omitempty"`
	Delta                  float64              `json:"delta,omitempty"`
	Gamma                  float64              `json:"gamma,omitempty"`
	Theta                  float64              `json:"theta,omitempty"`
	Vega                   float64              `json:"vega,omitempty"`
	Rho                    float64              `json:"rho,omitempty"`
	TimeValue              float64              `json:"timeValue,omitempty"`
	OpenInterest           float64              `json:"openInterest,omitempty"`
	IsInTheMoney           bool                 `json:"isInTheMoney,omitempty"`
	TheoreticalOptionValue float64              `json:"theoreticalOptionValue,omitempty"`
	TheoreticalVolatility  float64              `json:"theoreticalVolatility,omitempty"`
	IsMini                 bool                 `json:"isMini,omitempty"`
	IsNonStandard          bool                 `json:"isNonStandard,omitempty"`
	OptionDeliverablesList []OptionDeliverables `json:"optionDeliverablesList,omitempty"`
	StrikePrice            float64              `json:"strikePrice,omitempty"`
	ExpirationDate         string               `json:"expirationDate,omitempty"`
	DaysToExpiration       float64              `json:"daysToExpiration,omitempty"`
	ExpirationType         *ExpirationType      `json:"expirationType,omitempty"`
	LastTradingDay         float64              `json:"lastTradingDay,omitempty"`
	Multiplier             float64              `json:"multiplier,omitempty"`
	SettlementType         *SettlementType      `json:"settlementType,omitempty"`
	DeliverableNote        string               `json:"deliverableNote,omitempty"`
	IsIndexOption          bool                 `json:"isIndexOption,omitempty"`
	PercentChange          float64              `json:"percentChange,omitempty"`
	MarkChange             float64              `json:"markChange,omitempty"`
	MarkPercentChange      float64              `json:"markPercentChange,omitempty"`
	IsPennyPilot           bool                 `json:"isPennyPilot,omitempty"`
	IntrinsicValue         float64              `json:"intrinsicValue,omitempty"`
	OptionRoot             string               `json:"optionRoot,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OptionDeliverables struct {
	Symbol           string `json:"symbol,omitempty"`
	AssetType        string `json:"assetType,omitempty"`
	DeliverableUnits string `json:"deliverableUnits,omitempty"`
	CurrencyType     string `json:"currencyType,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote info of Option security
type OptionResponse struct {
	AssetMainType *AssetMainType `json:"assetMainType,omitempty"`
	// SSID of instrument
	Ssid int64 `json:"ssid,omitempty"`
	// Symbol of instrument
	Symbol string `json:"symbol,omitempty"`
	// is quote realtime
	Realtime  bool             `json:"realtime,omitempty"`
	Quote     *QuoteOption     `json:"quote,omitempty"`
	Reference *ReferenceOption `json:"reference,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Equity security
type QuoteEquity struct {
	// Higest price traded in the past 12 months, or 52 weeks
	Var52WeekHigh float64 `json:"52WeekHigh,omitempty"`
	// Lowest price traded in the past 12 months, or 52 weeks
	Var52WeekLow float64 `json:"52WeekLow,omitempty"`
	// ask MIC code
	AskMICId string `json:"askMICId,omitempty"`
	// Current Best Ask Price
	AskPrice float64 `json:"askPrice,omitempty"`
	// Number of shares for ask
	AskSize int32 `json:"askSize,omitempty"`
	// Last ask time in milliseconds since Epoch
	AskTime int64 `json:"askTime,omitempty"`
	// bid MIC code
	BidMICId string `json:"bidMICId,omitempty"`
	// Current Best Bid Price
	BidPrice float64 `json:"bidPrice,omitempty"`
	// Number of shares for bid
	BidSize int32 `json:"bidSize,omitempty"`
	// Last bid time in milliseconds since Epoch
	BidTime int64 `json:"bidTime,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Day's high trade price
	HighPrice float64 `json:"highPrice,omitempty"`
	// Last MIC Code
	LastMICId string  `json:"lastMICId,omitempty"`
	LastPrice float64 `json:"lastPrice,omitempty"`
	// Number of shares traded with last trade
	LastSize int32 `json:"lastSize,omitempty"`
	// Day's low trade price
	LowPrice float64 `json:"lowPrice,omitempty"`
	// Mark price
	Mark float64 `json:"mark,omitempty"`
	// Mark Price change
	MarkChange float64 `json:"markChange,omitempty"`
	// Mark Price percent change
	MarkPercentChange float64 `json:"markPercentChange,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange float64 `json:"netPercentChange,omitempty"`
	// Price at market open
	OpenPrice float64 `json:"openPrice,omitempty"`
	// Last quote time in milliseconds since Epoch
	QuoteTime int64 `json:"quoteTime,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
	// Option Risk/Volatility Measurement
	Volatility float64 `json:"volatility,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Partial or Custom errors per request
type QuoteError struct {
	// list of invalid cusips from request
	InvalidCusips []string `json:"invalidCusips,omitempty"`
	// list of invalid SSIDs from request
	InvalidSSIDs []int64 `json:"invalidSSIDs,omitempty"`
	// list of invalid symbols from request
	InvalidSymbols []string `json:"invalidSymbols,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Forex security
type QuoteForex struct {
	// Higest price traded in the past 12 months, or 52 weeks
	Var52WeekHigh float64 `json:"52WeekHigh,omitempty"`
	// Lowest price traded in the past 12 months, or 52 weeks
	Var52WeekLow float64 `json:"52WeekLow,omitempty"`
	// Current Best Ask Price
	AskPrice float64 `json:"askPrice,omitempty"`
	// Number of shares for ask
	AskSize int32 `json:"askSize,omitempty"`
	// Current Best Bid Price
	BidPrice float64 `json:"bidPrice,omitempty"`
	// Number of shares for bid
	BidSize int32 `json:"bidSize,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Day's high trade price
	HighPrice float64 `json:"highPrice,omitempty"`
	LastPrice float64 `json:"lastPrice,omitempty"`
	// Number of shares traded with last trade
	LastSize int32 `json:"lastSize,omitempty"`
	// Day's low trade price
	LowPrice float64 `json:"lowPrice,omitempty"`
	// Mark price
	Mark float64 `json:"mark,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange float64 `json:"netPercentChange,omitempty"`
	// Price at market open
	OpenPrice float64 `json:"openPrice,omitempty"`
	// Last quote time in milliseconds since Epoch
	QuoteTime int64 `json:"quoteTime,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// Tick Price
	Tick float64 `json:"tick,omitempty"`
	// Tick Amount
	TickAmount float64 `json:"tickAmount,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Future security
type QuoteFuture struct {
	// ask MIC code
	AskMICId string `json:"askMICId,omitempty"`
	// Current Best Ask Price
	AskPrice float64 `json:"askPrice,omitempty"`
	// Number of shares for ask
	AskSize int32 `json:"askSize,omitempty"`
	// Last ask time in milliseconds since Epoch
	AskTime int64 `json:"askTime,omitempty"`
	// bid MIC code
	BidMICId string `json:"bidMICId,omitempty"`
	// Current Best Bid Price
	BidPrice float64 `json:"bidPrice,omitempty"`
	// Number of shares for bid
	BidSize int32 `json:"bidSize,omitempty"`
	// Last bid time in milliseconds since Epoch
	BidTime int64 `json:"bidTime,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Net Percentage Change
	FuturePercentChange float64 `json:"futurePercentChange,omitempty"`
	// Day's high trade price
	HighPrice float64 `json:"highPrice,omitempty"`
	// Last MIC Code
	LastMICId string  `json:"lastMICId,omitempty"`
	LastPrice float64 `json:"lastPrice,omitempty"`
	// Number of shares traded with last trade
	LastSize int32 `json:"lastSize,omitempty"`
	// Day's low trade price
	LowPrice float64 `json:"lowPrice,omitempty"`
	// Mark price
	Mark float64 `json:"mark,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Open interest
	OpenInterest int32 `json:"openInterest,omitempty"`
	// Price at market open
	OpenPrice float64 `json:"openPrice,omitempty"`
	// Last quote time in milliseconds since Epoch
	QuoteTime int64 `json:"quoteTime,omitempty"`
	// quoted during trading session
	QuotedInSession bool `json:"quotedInSession,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// settlement time in milliseconds since Epoch
	SettleTime int64 `json:"settleTime,omitempty"`
	// Tick Price
	Tick float64 `json:"tick,omitempty"`
	// Tick Amount
	TickAmount float64 `json:"tickAmount,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Option security
type QuoteFutureOption struct {
	// ask MIC code
	AskMICId string `json:"askMICId,omitempty"`
	// Current Best Ask Price
	AskPrice float64 `json:"askPrice,omitempty"`
	// Number of shares for ask
	AskSize int32 `json:"askSize,omitempty"`
	// bid MIC code
	BidMICId string `json:"bidMICId,omitempty"`
	// Current Best Bid Price
	BidPrice float64 `json:"bidPrice,omitempty"`
	// Number of shares for bid
	BidSize int32 `json:"bidSize,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Day's high trade price
	HighPrice float64 `json:"highPrice,omitempty"`
	// Last MIC Code
	LastMICId string  `json:"lastMICId,omitempty"`
	LastPrice float64 `json:"lastPrice,omitempty"`
	// Number of shares traded with last trade
	LastSize int32 `json:"lastSize,omitempty"`
	// Day's low trade price
	LowPrice float64 `json:"lowPrice,omitempty"`
	// Mark price
	Mark float64 `json:"mark,omitempty"`
	// Mark Price change
	MarkChange float64 `json:"markChange,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange float64 `json:"netPercentChange,omitempty"`
	// Open Interest
	OpenInterest int32 `json:"openInterest,omitempty"`
	// Price at market open
	OpenPrice float64 `json:"openPrice,omitempty"`
	// Last quote time in milliseconds since Epoch
	QuoteTime int64 `json:"quoteTime,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// Price at market open
	SettlemetPrice float64 `json:"settlemetPrice,omitempty"`
	// Tick Price
	Tick float64 `json:"tick,omitempty"`
	// Tick Amount
	TickAmount float64 `json:"tickAmount,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Index security
type QuoteIndex struct {
	// Higest price traded in the past 12 months, or 52 weeks
	Var52WeekHigh float64 `json:"52WeekHigh,omitempty"`
	// Lowest price traded in the past 12 months, or 52 weeks
	Var52WeekLow float64 `json:"52WeekLow,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Day's high trade price
	HighPrice float64 `json:"highPrice,omitempty"`
	LastPrice float64 `json:"lastPrice,omitempty"`
	// Day's low trade price
	LowPrice float64 `json:"lowPrice,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange float64 `json:"netPercentChange,omitempty"`
	// Price at market open
	OpenPrice float64 `json:"openPrice,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Mutual Fund security
type QuoteMutualFund struct {
	// Higest price traded in the past 12 months, or 52 weeks
	Var52WeekHigh float64 `json:"52WeekHigh,omitempty"`
	// Lowest price traded in the past 12 months, or 52 weeks
	Var52WeekLow float64 `json:"52WeekLow,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Net Asset Value
	NAV float64 `json:"nAV,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange float64 `json:"netPercentChange,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Quote data of Option security
type QuoteOption struct {
	// Higest price traded in the past 12 months, or 52 weeks
	Var52WeekHigh float64 `json:"52WeekHigh,omitempty"`
	// Lowest price traded in the past 12 months, or 52 weeks
	Var52WeekLow float64 `json:"52WeekLow,omitempty"`
	// Current Best Ask Price
	AskPrice float64 `json:"askPrice,omitempty"`
	// Number of shares for ask
	AskSize int32 `json:"askSize,omitempty"`
	// Current Best Bid Price
	BidPrice float64 `json:"bidPrice,omitempty"`
	// Number of shares for bid
	BidSize int32 `json:"bidSize,omitempty"`
	// Previous day's closing price
	ClosePrice float64 `json:"closePrice,omitempty"`
	// Delta Value
	Delta float64 `json:"delta,omitempty"`
	// Gamma Value
	Gamma float64 `json:"gamma,omitempty"`
	// Day's high trade price
	HighPrice float64 `json:"highPrice,omitempty"`
	// Indicative Ask Price applicable only for Indicative Option Symbols
	IndAskPrice float64 `json:"indAskPrice,omitempty"`
	// Indicative Bid Price applicable only for Indicative Option Symbols
	IndBidPrice float64 `json:"indBidPrice,omitempty"`
	// Indicative Quote Time in milliseconds since Epoch applicable only for Indicative Option Symbols
	IndQuoteTime int64 `json:"indQuoteTime,omitempty"`
	// Implied Yield
	ImpliedYield float64 `json:"impliedYield,omitempty"`
	LastPrice    float64 `json:"lastPrice,omitempty"`
	// Number of shares traded with last trade
	LastSize int32 `json:"lastSize,omitempty"`
	// Day's low trade price
	LowPrice float64 `json:"lowPrice,omitempty"`
	// Mark price
	Mark float64 `json:"mark,omitempty"`
	// Mark Price change
	MarkChange float64 `json:"markChange,omitempty"`
	// Mark Price percent change
	MarkPercentChange float64 `json:"markPercentChange,omitempty"`
	// Money Intrinsic Value
	MoneyIntrinsicValue float64 `json:"moneyIntrinsicValue,omitempty"`
	// Current Last-Prev Close
	NetChange float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange float64 `json:"netPercentChange,omitempty"`
	// Open Interest
	OpenInterest float64 `json:"openInterest,omitempty"`
	// Price at market open
	OpenPrice float64 `json:"openPrice,omitempty"`
	// Last quote time in milliseconds since Epoch
	QuoteTime int64 `json:"quoteTime,omitempty"`
	// Rho Value
	Rho float64 `json:"rho,omitempty"`
	// Status of security
	SecurityStatus string `json:"securityStatus,omitempty"`
	// Theoretical option Value
	TheoreticalOptionValue float64 `json:"theoreticalOptionValue,omitempty"`
	// Theta Value
	Theta float64 `json:"theta,omitempty"`
	// Time Value
	TimeValue float64 `json:"timeValue,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime int64 `json:"tradeTime,omitempty"`
	// Underlying Price
	UnderlyingPrice float64 `json:"underlyingPrice,omitempty"`
	// Vega Value
	Vega float64 `json:"vega,omitempty"`
	// Option Risk/Volatility Measurement
	Volatility float64 `json:"volatility,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Request one or more quote data in POST body
type QuoteRequest struct {
	// List of cusip, max of 500 of symbols+cusip+ssids
	Cusips []string `json:"cusips,omitempty"`
	// comma separated list of nodes in each quote<br/> possible values are quote,fundamental,reference,extended,regular. Dont send this attribute for full response.
	Fields string `json:"fields,omitempty"`
	// List of Schwab securityid[SSID], max of 500 of symbols+cusip+ssids
	Ssids []int64 `json:"ssids,omitempty"`
	// List of symbols, max of 500 of symbols+cusip+ssids
	Symbols []string `json:"symbols,omitempty"`
	// Get realtime quotes and skip entitlement check
	Realtime bool `json:"realtime,omitempty"`
	// Include indicative symbol quotes for all ETF symbols in request. If ETF symbol ABC is in request and indicative=true API will return quotes for ABC and its corresponding indicative quote for $ABC.IV
	Indicative bool `json:"indicative,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type QuoteResponseObject struct {
	EquityResponse
	OptionResponse
	ForexResponse
	FutureResponse
	FutureOptionResponse
	IndexResponse
	MutualFundResponse
	QuoteError
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// QuoteType : NBBO - realtime, NFL - Non-fee liable quote.
type QuoteType string

// List of QuoteType
const (
	NBBO_QuoteType QuoteType = "NBBO"
	NFL_QuoteType  QuoteType = "NFL"
	NULL_QuoteType QuoteType = ""
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of Equity security
type ReferenceEquity struct {
	// CUSIP of Instrument
	Cusip string `json:"cusip,omitempty"`
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string `json:"exchangeName,omitempty"`
	// FSI Desc
	FsiDesc string `json:"fsiDesc,omitempty"`
	// Hard to borrow quantity.
	HtbQuantity int32 `json:"htbQuantity,omitempty"`
	// Hard to borrow rate.
	HtbRate float64 `json:"htbRate,omitempty"`
	// is Hard to borrow security.
	IsHardToBorrow bool `json:"isHardToBorrow,omitempty"`
	// is shortable security.
	IsShortable bool `json:"isShortable,omitempty"`
	// OTC Market Tier
	OtcMarketTier string `json:"otcMarketTier,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of Forex security
type ReferenceForex struct {
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string `json:"exchangeName,omitempty"`
	// is FOREX tradable
	IsTradable bool `json:"isTradable,omitempty"`
	// Market marker
	MarketMaker string `json:"marketMaker,omitempty"`
	// Product name
	Product string `json:"product,omitempty"`
	// Trading hours
	TradingHours string `json:"tradingHours,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of Future security
type ReferenceFuture struct {
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string `json:"exchangeName,omitempty"`
	// Active symbol
	FutureActiveSymbol string `json:"futureActiveSymbol,omitempty"`
	// Future expiration date in milliseconds since epoch
	FutureExpirationDate float64 `json:"futureExpirationDate,omitempty"`
	// Future is active
	FutureIsActive bool `json:"futureIsActive,omitempty"`
	// Future multiplier
	FutureMultiplier float64 `json:"futureMultiplier,omitempty"`
	// Price format
	FuturePriceFormat string `json:"futurePriceFormat,omitempty"`
	// Future Settlement Price
	FutureSettlementPrice float64 `json:"futureSettlementPrice,omitempty"`
	// Trading Hours
	FutureTradingHours string `json:"futureTradingHours,omitempty"`
	// Futures product symbol
	Product string `json:"product,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of Future Option security
type ReferenceFutureOption struct {
	ContractType *ContractType `json:"contractType,omitempty"`
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string `json:"exchangeName,omitempty"`
	// Option multiplier
	Multiplier float64 `json:"multiplier,omitempty"`
	// date of expiration in long
	ExpirationDate int64 `json:"expirationDate,omitempty"`
	// Style of expiration
	ExpirationStyle string `json:"expirationStyle,omitempty"`
	// Strike Price
	StrikePrice float64 `json:"strikePrice,omitempty"`
	// A company, index or fund name
	Underlying string `json:"underlying,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of Index security
type ReferenceIndex struct {
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string `json:"exchangeName,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of MutualFund security
type ReferenceMutualFund struct {
	// CUSIP of Instrument
	Cusip string `json:"cusip,omitempty"`
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string `json:"exchangeName,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Reference data of Option security
type ReferenceOption struct {
	ContractType *ContractType `json:"contractType,omitempty"`
	// CUSIP of Instrument
	Cusip string `json:"cusip,omitempty"`
	// Days to Expiration
	DaysToExpiration int32 `json:"daysToExpiration,omitempty"`
	// Unit of trade
	Deliverables string `json:"deliverables,omitempty"`
	// Description of Instrument
	Description string `json:"description,omitempty"`
	// Exchange Code
	Exchange string `json:"exchange,omitempty"`
	// Exchange Name
	ExchangeName string        `json:"exchangeName,omitempty"`
	ExerciseType *ExerciseType `json:"exerciseType,omitempty"`
	// Expiration Day
	ExpirationDay int32 `json:"expirationDay,omitempty"`
	// Expiration Month
	ExpirationMonth int32           `json:"expirationMonth,omitempty"`
	ExpirationType  *ExpirationType `json:"expirationType,omitempty"`
	// Expiration Year
	ExpirationYear int32 `json:"expirationYear,omitempty"`
	// Is this contract part of the Penny Pilot program
	IsPennyPilot bool `json:"isPennyPilot,omitempty"`
	// milliseconds since epoch
	LastTradingDay int64 `json:"lastTradingDay,omitempty"`
	// Option multiplier
	Multiplier     float64         `json:"multiplier,omitempty"`
	SettlementType *SettlementType `json:"settlementType,omitempty"`
	// Strike Price
	StrikePrice float64 `json:"strikePrice,omitempty"`
	// A company, index or fund name
	Underlying string `json:"underlying,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Market info of security
type RegularMarket struct {
	// Regular market last price
	RegularMarketLastPrice float64 `json:"regularMarketLastPrice,omitempty"`
	// Regular market last size
	RegularMarketLastSize int32 `json:"regularMarketLastSize,omitempty"`
	// Regular market net change
	RegularMarketNetChange float64 `json:"regularMarketNetChange,omitempty"`
	// Regular market percent change
	RegularMarketPercentChange float64 `json:"regularMarketPercentChange,omitempty"`
	// Regular market trade time in milliseconds since Epoch
	RegularMarketTradeTime int64 `json:"regularMarketTradeTime,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Security info of most moved with in an index
type Screener struct {
	// percent or value changed, by default its percent changed
	Change float64 `json:"change,omitempty"`
	// Name of security
	Description string `json:"description,omitempty"`
	Direction   string `json:"direction,omitempty"`
	// what was last quoted price
	Last float64 `json:"last,omitempty"`
	// schwab security symbol
	Symbol      string `json:"symbol,omitempty"`
	TotalVolume int64  `json:"totalVolume,omitempty"`
}

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// SettlementType : option contract settlement type AM or PM
type SettlementType string

// List of SettlementType
const (
	A_SettlementType SettlementType = "A"
	P_SettlementType SettlementType = "P"
)

/*
 * Market Data
 *
 * Trader API - Market data
 *
 * API version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Underlying struct {
	Ask               float64 `json:"ask,omitempty"`
	AskSize           int32   `json:"askSize,omitempty"`
	Bid               float64 `json:"bid,omitempty"`
	BidSize           int32   `json:"bidSize,omitempty"`
	Change            float64 `json:"change,omitempty"`
	Close             float64 `json:"close,omitempty"`
	Delayed           bool    `json:"delayed,omitempty"`
	Description       string  `json:"description,omitempty"`
	ExchangeName      string  `json:"exchangeName,omitempty"`
	FiftyTwoWeekHigh  float64 `json:"fiftyTwoWeekHigh,omitempty"`
	FiftyTwoWeekLow   float64 `json:"fiftyTwoWeekLow,omitempty"`
	HighPrice         float64 `json:"highPrice,omitempty"`
	Last              float64 `json:"last,omitempty"`
	LowPrice          float64 `json:"lowPrice,omitempty"`
	Mark              float64 `json:"mark,omitempty"`
	MarkChange        float64 `json:"markChange,omitempty"`
	MarkPercentChange float64 `json:"markPercentChange,omitempty"`
	OpenPrice         float64 `json:"openPrice,omitempty"`
	PercentChange     float64 `json:"percentChange,omitempty"`
	QuoteTime         int64   `json:"quoteTime,omitempty"`
	Symbol            string  `json:"symbol,omitempty"`
	TotalVolume       int64   `json:"totalVolume,omitempty"`
	TradeTime         int64   `json:"tradeTime,omitempty"`
}
